'use client'

import { ChakraProvider, extendTheme } from "@chakra-ui/react"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const fonts = {
  body: 'Nunito',
  heading: 'Raleway'
}

const theme = extendTheme({
  fonts
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><ChakraProvider theme={theme}>{children}</ChakraProvider></body>
    </html>
  )
}
