'use client'

import { ChakraProvider } from "@chakra-ui/react"
import theme from "./components/theme"
import './components/theme/styles.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><ChakraProvider theme={theme}>{children}</ChakraProvider></body>
    </html>
  )
}
